apiVersion: v1
appVersion: "0.1.0-alpha.23"
description: Trinity, Python Ethereum (1.0 & 2.0) Node Client 
name: trinity
home: https://trinity.ethereum.org/
icon: https://trinity.ethereum.org/images/trinity-logo-icon.svg
version: 0.1.0
keywords:
  - ethereum
  - python
  - blockchain
  - evm
  - crypto
maintainers:
  - name: Gabriel Smadi
    email: gabriel@smadi.ci
    url: http://smadi.ci
sources:
  - https://github.com/ethereum/trinity
  - https://trinity-client.readthedocs.io/en/latest/
  - https://hub.docker.com/r/ethereum/trinity
