apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "trinity.name" . }}
    helm.sh/chart: {{ include "trinity.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  WS_SECRET: {{ .Values.ethstatsSecret | b64enc | quote }}
